# Usage:
# kubectl create -f https://raw.githubusercontent.com/wilbeibi/recipes/master/cloud/netshoot/netshoot.yaml
# kubectl exec netshoot -i -t -- ping <IP>
# kubectl exec netshoot -i -t -- nslookup <domain name>
apiVersion: v1
kind: Pod
metadata:
  name: swagger
  labels:
    name: swagger
spec:
  containers:
  - name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP    