apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - name: server
    image: wilbeibi/server_demo
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP    