FROM debian:stable-slim
# TODO
# 1. kube-prompt
# wget https://github.com/c-bata/kube-prompt/releases/download/v1.0.5/kube-prompt_v1.0.5_linux_amd64.zip
# unzip kube-prompt_v1.0.5_linux_amd64.zip && chmod

# 2. kube-ctx
# sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
# sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
# sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens
# or sudo apt install kubectx

# 3. kubetail
# https://github.com/johanhaleby/kubetail

# 4. click
# https://github.com/databricks/click

# mount ~/.kube

# make a alias command