# Usage:
# kubectl create -f https://raw.githubusercontent.com/wilbeibi/recipes/master/cloud/netshoot/netshoot.yaml
# kubectl exec netshoot -i -t -- ping <IP>
# kubectl exec netshoot -i -t -- nslookup <domain name>
apiVersion: v1
kind: Pod
metadata:
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: wilbeibi/netshoot:v0.4
    command:
      - sleep
      - "10000"
