#!/usr/bin/env python3

import os
import sys
from subprocess import Popen, PIPE
from multiprocessing import Pool

""" Recursively execute git command
    >> rgit pull
    >> rgit gc
"""

GIT = "/usr/local/bin/git"


def get_repos(root_dir, git_cmd):
    for dirname, dirnames, filenames in os.walk(root_dir):
        for subdirname in dirnames:
            if ".git" == subdirname:
                git_path = os.path.abspath(dirname) + "/.git"
                command = f"{GIT} --git-dir={git_path} {git_cmd}"
                yield command


def exec_cmd(command):
    print(command)
    proc = Popen([command], stdout=PIPE, shell=True)
    output = proc.communicate()[0]
    print(output.decode())
    print('\n')


def do_all(git_cmd):
    pool = Pool(5)
    pool.map(exec_cmd, get_repos(".", git_cmd))
    pool.close()
    pool.join()


if __name__ == '__main__':
    if len(sys.argv) != 2 or sys.argv[1] not in ("pull", "gc"):
        print("Usage : rgit <cmd>")
        sys.exit(1)
    do_all(sys.argv[1])
